version: '3'

services:
  api:
    container_name: nft-marketplace-api
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "3001:3001"
    volumes:
      - ./src/api:/api
      - ./src/api/node_modules:/api/node_modules
    depends_on:
      - db

  app:
    container_name: nft-marketplace-app
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "3000:3000"
    volumes:
      - ./src/app:/app
      - /app/node_modules
    depends_on:
      - api

  db:
    container_name: nft-marketplace-db
    image: postgres:15.7
    env_file:
      - ./docker/.env
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data

  pgadmin:
    container_name: nft-marketplace-pgadmin
    image: dpage/pgadmin4:8.12
    env_file:
      - ./docker/.env
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgresdata:
    driver: local
  pgadmin_data:
    driver: local
